### ISSUE TITLE
If you connect to mongodb, fault-tolerant does not work.

### ISSUE THREAD

**Issue by pruge** [dashersw/cote#167] opened 2019-05-23 11:34 UTC
If you run the requester first and run the responder,
It does not respond.
Do I have something wrong?

```
// requester
const cote = require('cote');

const requester = new cote.Requester({ name: 'currency conversion requester' });
const request = { type: 'convert', from: 'usd', to: 'eur', amount: 10 };

requester.send(request)
  .then((res) => {
    console.log(res);
  });
```

```
// responder
const cote = require('cote');
const Promise = require('bluebird');
const mongoose = require('mongoose');

const responder = new cote.Responder({ name: 'currency conversion responder' });
const rates = { usd_eur: 0.91, eur_usd: 1.10 };

const start = async () => {
  await new Promise((resolve, reject) => {
    const url = '...';

    mongoose.connect(url, { useNewUrlParser: true });
    const db = mongoose.connection;

    db.on('error', err => {
      console.log('Mongodb error encounterd [' + err + ']');
      reject(err);
      process.exit(1);
    });

    // when open
    db.once('open', () => {
      console.log('-- Mongodb is connected');
      resolve(db);
    });
  });

  responder.on('convert', async (req) => {
    console.log(req.amount * rates[`${req.from}_${req.to}`]);
    return (req.amount * rates[`${req.from}_${req.to}`]);
  });

};

start()
  .catch(err => console.log(err));
```

**Comment by pruge** [comment] 2019-05-24 04:35
can be reproduced when:

Creates a responder object.
After a certain period of time, register the event.
fault-tolerant does not work.

```
// requester
const cote = require('cote');

const requester = new cote.Requester({ name: 'currency conversion requester' });
const request = { type: 'convert', from: 'usd', to: 'eur', amount: 10 };

requester.send(request)
  .then((res) => {
    console.log(res);
  });
```

```
// responder
const cote = require('cote');
const hoek = require('@hapi/hoek');

const rates = { usd_eur: 0.91, eur_usd: 1.10 };

const start = async () => {
  const responder = new cote.Responder({ name: 'currency conversion responder' });

  await hoek.wait(1000); 
 
  responder.on('convert', async (req) => {
    console.log(req.amount * rates[`${req.from}_${req.to}`]);
    return (req.amount * rates[`${req.from}_${req.to}`]);
  });

};

start()
  .catch(err => console.log(err));
```

**Comment by dashersw** [comment] 2019-05-24 08:53
Could it be because you are not using native Promises?

**Comment by pruge** [comment] 2019-05-24 10:16
It seems to happen regardless of the native promise.

**Comment by dashersw** [comment] 2019-05-25 13:57
Oh sorry, I didn’t see the code example. It’s because the event registration is async — is it possible to do `responder.on` calls in sync with instantiation of the Responder?

**Comment by pruge** [comment] 2019-05-25 14:28
I do not think it's a matter of synchronous or asynchronous.
It does not work either.

**Comment by dashersw** [comment] 2019-05-25 14:29
```js
const cote = require('cote');
const hoek = require('@hapi/hoek');

const rates = { usd_eur: 0.91, eur_usd: 1.10 };

const start = async () => {
  await hoek.wait(1000); 

  const responder = new cote.Responder({ name: 'currency conversion responder' });
 
  responder.on('convert', async (req) => {
    console.log(req.amount * rates[`${req.from}_${req.to}`]);
    return (req.amount * rates[`${req.from}_${req.to}`]);
  });

};

start()
  .catch(err => console.log(err));
```

Can you try this? It should work.

**Comment by pruge** [comment] 2019-05-25 14:31
Yes The code you uploaded works.
However, the problem is that it does not work if there is something between the responder object and the event registration.

**Comment by dashersw** [comment] 2019-05-25 14:34
Yes, and that is unfortunately by design. The responder publishes its capabilities as soon as it’s online, and at that time, there are no event handlers. The requester sees a responder online, and releases the message. What is the use case that requires to separate handler registration and component instantiation? Can you do them together?

**Comment by pruge** [comment] 2019-05-25 14:45
Very strange.
run a.js -> b.js -> c.js

requester lost.

If it does not work in sequence, is there a problem?
```
// a.js
// requester
const cote = require('cote');

const requester = new cote.Requester({ name: 'currency conversion requester' });
const request = { type: 'convert', from: 'usd', to: 'eur', amount: 10 };

requester.send(request)
  .then((res) => {
    console.log(res);
  });
```
```
// b.js
// responder
const cote = require('cote');
const hoek = require('@hapi/hoek');

const rates = { usd_eur: 0.91, eur_usd: 1.10 };

const start = async () => {
  const responder = new cote.Responder({ name: 'currency conversion responder2' });

  await hoek.wait(1000);
};

start()
  .catch(err => console.log(err));
```

```
// c.js
// responder
const cote = require('cote');

const rates = { usd_eur: 0.91, eur_usd: 1.10 };

const start = async () => {
  const responder = new cote.Responder({ name: 'currency conversion responder' });

  responder.on('convert', async (req) => {
    console.log(req.amount * rates[`${req.from}_${req.to}`]);
    return (req.amount * rates[`${req.from}_${req.to}`]);
  });

};

start()
  .catch(err => console.log(err));
```

**Comment by dashersw** [comment] 2019-05-25 14:49
It looks like you don’t have an event handler on b — cote doesn’t do event mapping. All the responders will receive events (regardless of whether they have handlers for that event or not) from the requesters in the same key (in this case, the global key).

Since b doesn’t have a handler, it receives the message, but throws it away. If it also has a `convert` handler, it will work. If you need to have different types of messages in b and c, you should use keys or namespaces. You can read more about them in the readme.

**Comment by pruge** [comment] 2019-05-25 14:52
b.js has been fixed.
It still does not work.
So there is a risk that the request will disappear at any time?

**Comment by dashersw** [comment] 2019-05-25 14:57
As I said, in this case, you are using multiple event names on different responders. In order for this to work, you need to start using keys. That means you would have two separate requesters for each group of messages (sum is one and convert is another) and use different keys with them. Responders should also use the same — conversion responder should be in the convert key, sum responder should be in the sum key.

In this case, there won’t be any lost requests.

**Comment by pruge** [comment] 2019-05-25 15:05
I understand that cote supports mesh networks.
If it is separated by a key, is not it different from one-to-one correspondence?

**Comment by dashersw** [comment] 2019-05-25 15:10
It is a mesh network — in that you can have as many instances as you want of a set of messages, and there will be inter-communication between them. It’s also the case that one node application can host multiple requesters and responders in different keys. This is an efficient mesh network implementation —- if requesters and responders won’t be able to communicate with each other (because they ask for and serve different messages) there’s no need for a connection. This reduces the network gossip.

As long as b and c can respond to the same events, a will connect to both and you won’t run into any issues.

**Comment by dashersw** [comment] 2019-05-25 15:11
You can see the keys in effect here: https://github.com/dashersw/cote-examples-currency-conversion

**Comment by pruge** [comment] 2019-05-25 15:31
I understand how it is structured.
Thank you very much for kindly explaining.

**Comment by dashersw** [comment] 2019-05-25 15:39
Any time! If you have any other questions or issues, feel free to reach out either here or on our Slack.

**Closed** 2019-05-27 13:58 UTC
